create table public.customers (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 160),
  phone text not null check (char_length(trim(phone)) between 1 and 40),
  address text not null check (char_length(trim(address)) between 1 and 500),
  map_url text not null default '' check (map_url = '' or map_url ~ '^https://'),
  preferred_call_day integer not null default 25 check (preferred_call_day between 1 and 31),
  preferred_delivery_day integer not null default 1 check (preferred_delivery_day between 1 and 31),
  notes text not null default '' check (char_length(notes) <= 1000),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_customers_active_name on public.customers (is_active, name);

create table public.products (
  id bigint generated by default as identity primary key,
  product_code integer not null unique check (product_code between 1 and 10000000),
  product_name text not null check (char_length(trim(product_name)) between 1 and 200),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_products_active_name on public.products (is_active, product_name);

create table public.usual_order_items (
  customer_id bigint not null references public.customers(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity integer not null check (quantity between 1 and 1000000),
  primary key (customer_id, product_id)
);

create table public.monthly_orders (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id),
  order_month text not null check (order_month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  status text not null default 'draft' check (status in ('draft', 'call_again', 'confirmed', 'skipped')),
  next_call_at timestamptz,
  delivery_date date,
  contact_note text not null default '' check (char_length(contact_note) <= 1000),
  confirmed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (customer_id, order_month)
);

create index idx_orders_month_status on public.monthly_orders (order_month, status);
create index idx_orders_delivery_date on public.monthly_orders (delivery_date);

create table public.monthly_order_items (
  order_id bigint not null references public.monthly_orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  product_code_snapshot integer not null check (product_code_snapshot between 1 and 10000000),
  product_name_snapshot text not null,
  quantity integer not null check (quantity between 1 and 1000000),
  primary key (order_id, product_id)
);

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid,
  action text not null,
  entity_type text not null,
  entity_id bigint,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index idx_audit_entity on public.audit_logs (entity_type, entity_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger customers_set_updated_at before update on public.customers
for each row execute function public.set_updated_at();
create trigger products_set_updated_at before update on public.products
for each row execute function public.set_updated_at();
create trigger monthly_orders_set_updated_at before update on public.monthly_orders
for each row execute function public.set_updated_at();

create or replace function public.audit_data_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  record_json jsonb;
  resolved_id bigint;
begin
  record_json := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  resolved_id := coalesce(
    nullif(record_json ->> 'id', '')::bigint,
    nullif(record_json ->> 'order_id', '')::bigint,
    nullif(record_json ->> 'customer_id', '')::bigint
  );
  insert into public.audit_logs (actor_id, action, entity_type, entity_id)
  values (auth.uid(), lower(tg_op), tg_table_name, resolved_id);
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

create trigger customers_audit after insert or update or delete on public.customers
for each row execute function public.audit_data_change();
create trigger products_audit after insert or update or delete on public.products
for each row execute function public.audit_data_change();
create trigger usual_order_items_audit after insert or update or delete on public.usual_order_items
for each row execute function public.audit_data_change();
create trigger monthly_orders_audit after insert or update or delete on public.monthly_orders
for each row execute function public.audit_data_change();
create trigger monthly_order_items_audit after insert or update or delete on public.monthly_order_items
for each row execute function public.audit_data_change();

create or replace function public.replace_usual_order_items(p_customer_id bigint, p_items jsonb)
returns void
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if jsonb_typeof(coalesce(p_items, '[]'::jsonb)) <> 'array' then
    raise exception 'items must be an array';
  end if;

  delete from public.usual_order_items where customer_id = p_customer_id;
  insert into public.usual_order_items (customer_id, product_id, quantity)
  select
    p_customer_id,
    (item ->> 'productId')::bigint,
    (item ->> 'quantity')::integer
  from jsonb_array_elements(coalesce(p_items, '[]'::jsonb)) item
  where (item ->> 'quantity')::integer > 0;
end;
$$;

create or replace function public.create_monthly_order(p_customer_id bigint, p_order_month text)
returns bigint
language plpgsql
set search_path = public, pg_temp
as $$
declare
  new_order_id bigint;
begin
  if p_order_month !~ '^\d{4}-(0[1-9]|1[0-2])$' then
    raise exception 'invalid order month';
  end if;

  insert into public.monthly_orders (customer_id, order_month)
  values (p_customer_id, p_order_month)
  on conflict (customer_id, order_month) do update set updated_at = now()
  returning id into new_order_id;

  insert into public.monthly_order_items
    (order_id, product_id, product_code_snapshot, product_name_snapshot, quantity)
  select new_order_id, usual.product_id, product.product_code, product.product_name, usual.quantity
  from public.usual_order_items usual
  join public.products product on product.id = usual.product_id
  where usual.customer_id = p_customer_id and product.is_active
  on conflict (order_id, product_id) do nothing;

  return new_order_id;
end;
$$;

create or replace function public.generate_monthly_orders(p_order_month text)
returns integer
language plpgsql
set search_path = public, pg_temp
as $$
declare
  affected integer;
begin
  if p_order_month !~ '^\d{4}-(0[1-9]|1[0-2])$' then
    raise exception 'invalid order month';
  end if;

  insert into public.monthly_orders (customer_id, order_month)
  select id, p_order_month from public.customers where is_active
  on conflict (customer_id, order_month) do nothing;
  get diagnostics affected = row_count;

  insert into public.monthly_order_items
    (order_id, product_id, product_code_snapshot, product_name_snapshot, quantity)
  select order_row.id, usual.product_id, product.product_code, product.product_name, usual.quantity
  from public.monthly_orders order_row
  join public.usual_order_items usual on usual.customer_id = order_row.customer_id
  join public.products product on product.id = usual.product_id
  where order_row.order_month = p_order_month and product.is_active
  on conflict (order_id, product_id) do nothing;

  return affected;
end;
$$;

create or replace function public.save_monthly_order(
  p_order_id bigint,
  p_status text,
  p_next_call_at timestamptz,
  p_delivery_date date,
  p_contact_note text,
  p_items jsonb
)
returns void
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if p_status not in ('draft', 'call_again', 'confirmed', 'skipped') then
    raise exception 'invalid order status';
  end if;
  if jsonb_typeof(coalesce(p_items, '[]'::jsonb)) <> 'array' then
    raise exception 'items must be an array';
  end if;

  update public.monthly_orders
  set status = p_status,
      next_call_at = p_next_call_at,
      delivery_date = p_delivery_date,
      contact_note = coalesce(p_contact_note, ''),
      confirmed_at = case when p_status = 'confirmed' then now() else null end
  where id = p_order_id;
  if not found then raise exception 'order not found'; end if;

  delete from public.monthly_order_items where order_id = p_order_id;
  insert into public.monthly_order_items
    (order_id, product_id, product_code_snapshot, product_name_snapshot, quantity)
  select
    p_order_id,
    product.id,
    product.product_code,
    product.product_name,
    (item ->> 'quantity')::integer
  from jsonb_array_elements(coalesce(p_items, '[]'::jsonb)) item
  join public.products product on product.id = (item ->> 'productId')::bigint
  where product.is_active and (item ->> 'quantity')::integer > 0;
end;
$$;

alter table public.customers enable row level security;
alter table public.products enable row level security;
alter table public.usual_order_items enable row level security;
alter table public.monthly_orders enable row level security;
alter table public.monthly_order_items enable row level security;
alter table public.audit_logs enable row level security;

revoke all on public.customers, public.products, public.usual_order_items,
  public.monthly_orders, public.monthly_order_items, public.audit_logs from anon;

grant select, insert, update, delete on public.customers, public.products,
  public.usual_order_items, public.monthly_orders, public.monthly_order_items to authenticated;
grant select on public.audit_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy authenticated_customers on public.customers for all to authenticated using (true) with check (true);
create policy authenticated_products on public.products for all to authenticated using (true) with check (true);
create policy authenticated_usual_orders on public.usual_order_items for all to authenticated using (true) with check (true);
create policy authenticated_monthly_orders on public.monthly_orders for all to authenticated using (true) with check (true);
create policy authenticated_monthly_order_items on public.monthly_order_items for all to authenticated using (true) with check (true);
create policy authenticated_audit_read on public.audit_logs for select to authenticated using (true);

revoke all on function public.replace_usual_order_items(bigint, jsonb) from public, anon;
revoke all on function public.create_monthly_order(bigint, text) from public, anon;
revoke all on function public.generate_monthly_orders(text) from public, anon;
revoke all on function public.save_monthly_order(bigint, text, timestamptz, date, text, jsonb) from public, anon;
grant execute on function public.replace_usual_order_items(bigint, jsonb) to authenticated;
grant execute on function public.create_monthly_order(bigint, text) to authenticated;
grant execute on function public.generate_monthly_orders(text) to authenticated;
grant execute on function public.save_monthly_order(bigint, text, timestamptz, date, text, jsonb) to authenticated;
